<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBYjuAGi\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBYjuAGi/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBYjuAGi.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBYjuAGi\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBYjuAGi\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BYjuAGi',
    'container.build_id' => '640b8943',
    'container.build_time' => 1549803934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBYjuAGi');
